[workspace]
members = ["aggregator", "circuit", "prover", "verifier"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.98", default-features = false }
plonky2 = { git = "https://github.com/Quantus-Network/plonky2", default-features = true }
hex = { version = "0.4.3" }
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = { version = "0.9.1" }


[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Quantus Network"]
description = "Wormhole circuit implementation using Plonky2"
license = "MIT"
