[package]
name = "wormhole-verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
plonky2.workspace = true
wormhole-circuit = { path = "../circuit" }

[dev-dependencies]
wormhole-prover = { path = "../prover" }
criterion = { workspace = true }

[features]
testing = ["wormhole-circuit/testing", "wormhole-prover/testing"]

[[bench]]
name = "verifier_bench"
harness = false
required-features = ["testing"]
